<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
        <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Mediator.Abstractions" Version="3.0.0-preview.53" />
        <PackageReference Include="Mediator.SourceGenerator" Version="3.0.0-preview.53">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.2"/>
        <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.11.8" />
        <PackageReference Include="Ulid" Version="1.3.4" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\components\src\Pure.Blazor.Components.Icons\Pure.Blazor.Components.Icons.csproj" />
      <ProjectReference Include="..\..\..\components\src\Pure.Blazor.Components\Pure.Blazor.Components.csproj" />
    </ItemGroup>

</Project>
